cards = {"cards":[{"title":"The Fool",
        "major_arcana":True,
        "id":0,
        "keywords":[],
        "picture":"",
            },
        {"title":"The Magician",
        "major_arcana":True,
        "id":1,
        "keywords":[],
        "picture":"",
            },
        {"title":"The High Priestess",
        "major_arcana":True,
        "id":2,
        "keywords":[],
        "picture":"",
            },
        {"title":"The Empress",
        "major_arcana":True,
        "id":3,
        "keywords":[],
        "picture":"",
            },
        {"title":"The Emperor",
        "major_arcana":True,
        "id":4,
        "keywords":[],
        "picture":"",
            },
        {"title":"The Hierophant",
        "major_arcana":True,
        "id":5,
        "keywords":[],
        "picture":"",
            },
        {"title":"The Lovers",
        "major_arcana":True,
        "id":6,
        "keywords":[],
        "picture":"",
            },
        {"title":"The Chariot",
        "major_arcana":True,
        "id":7,
        "keywords":[],
        "picture":"",
            },
        {"title":"The Strength",
        "major_arcana":True,
        "id":8,
        "keywords":[],
        "picture":"",
            },
        {"title":"The Hermit",
        "major_arcana":True,
        "id":9,
        "keywords":[],
        "picture":"",
            },
        {"title":"The Wheel of Fortune",
        "major_arcana":True,
        "id":10,
        "keywords":[],
        "picture":"",
            },
        {"title":"The Justice",
        "major_arcana":True,
        "id":11,
        "keywords":[],
        "picture":"",
            },
        {"title":"The Hanged Man",
        "major_arcana":True,
        "id":12,
        "keywords":[],
        "picture":"",
            },
        {"title":"The Death",
        "major_arcana":True,
        "id":13,
        "keywords":[],
        "picture":"",
            },
        {"title":"The Temperance",
        "major_arcana":True,
        "id":14,
        "keywords":[],
        "picture":"",
            },
        {"title":"The Devil",
        "major_arcana":True,
        "id":15,
        "keywords":[],
        "picture":"",
            },
        {"title":"The Tower",
        "major_arcana":True,
        "id":16,
        "keywords":[],
        "picture":"",
            },
        {"title":"The Star",
        "major_arcana":True,
        "id":17,
        "keywords":[],
        "picture":"",
            },
        {"title":"The Moon",
        "major_arcana":True,
        "id":18,
        "keywords":[],
        "picture":"",
            },
        {"title":"The Sun",
        "major_arcana":True,
        "id":19,
        "keywords":[],
        "picture":"",
            },
        {"title":"The Judgement",
        "major_arcana":True,
        "id":20,
        "keywords":[],
        "picture":"",
            },
        {"title":"The World",
        "major_arcana":True,
        "id":22,
        "keywords":[],
        "picture":"",
            },
        {"title":"",
        "major_arcana":"",
        "id":"",
        "keywords":[],
        "picture":"",
            }]
        }
