cards = {"cards":[{"title":"The Fool",
        "major_arcana":True,
        "id":0,
        "keywords":['Ignorance','Innocence', 'Begginings', 'Freedom'],
        "picture":"https://raw.githubusercontent.com/AlmirPaulo/TarotAPI/main/cards/rws/0.jpg",
            },
        {"title":"The Magician",
        "major_arcana":True,
        "id":1,
        "keywords":['Skill', 'Rogueness', 'Intelligence', 'To take action'],
        "picture":"https://raw.githubusercontent.com/AlmirPaulo/TarotAPI/main/cards/rws/1.jpg",
            },
        {"title":"The High Priestess",
        "major_arcana":True,
        "id":2,
        "keywords":['Silence', 'Secrets', 'Intuition'],
        "picture":"https://raw.githubusercontent.com/AlmirPaulo/TarotAPI/main/cards/rws/2.jpg",
            },
        {"title":"The Empress",
        "major_arcana":True,
        "id":3,
        "keywords":['Mother', 'Feminine', 'Fertility', 'Abundance', 'Creation'],
        "picture":"https://raw.githubusercontent.com/AlmirPaulo/TarotAPI/main/cards/rws/3.jpg",
            },
        {"title":"The Emperor",
        "major_arcana":True,
        "id":4,
        "keywords":['Father', 'Masculine', 'Power', 'Authority'],
        "picture":"https://raw.githubusercontent.com/AlmirPaulo/TarotAPI/main/cards/rws/4.jpg",
            },
        {"title":"The Hierophant", 
        "major_arcana":True,
        "id":5,
        "keywords":['Dogma', 'Wisdom Master', 'Structure'],
        "picture":"https://raw.githubusercontent.com/AlmirPaulo/TarotAPI/main/cards/rws/5.jpg",
            },
        {"title":"The Lovers",
        "major_arcana":True,
        "id":6,
        "keywords":['Choices', 'Decisions'],
        "picture":"https://raw.githubusercontent.com/AlmirPaulo/TarotAPI/main/cards/rws/6.jpg",
            },
        {"title":"The Chariot",
        "major_arcana":True,
        "id":7,
        "keywords":['Will power', 'Movements'],
        "picture":"https://raw.githubusercontent.com/AlmirPaulo/TarotAPI/main/cards/rws/7.jpg",
            },
        {"title":"The Strength",
        "major_arcana":True,
        "id":8,
        "keywords":['Control', 'Self-control', 'Courage'],
        "picture":"https://raw.githubusercontent.com/AlmirPaulo/TarotAPI/main/cards/rws/8.jpg",
            },
        {"title":"The Hermit",
        "major_arcana":True,
        "id":9,
        "keywords":['Loneliness', 'Solitude', 'Time for meditation'],
        "picture":"https://raw.githubusercontent.com/AlmirPaulo/TarotAPI/main/cards/rws/9.jpg",
            },
        {"title":"The Wheel of Fortune",
        "major_arcana":True,
        "id":10,
        "keywords":['Cycles', 'Luck'],
        "picture":"https://raw.githubusercontent.com/AlmirPaulo/TarotAPI/main/cards/rws/10.jpg",
            },
        {"title":"The Justice",
        "major_arcana":True,
        "id":11,
        "keywords":['Rationality', 'Justice', 'Fairness'],
        "picture":"https://raw.githubusercontent.com/AlmirPaulo/TarotAPI/main/cards/rws/11.jpg",
            },
        {"title":"The Hanged Man",
        "major_arcana":True,
        "id":12,
        "keywords":['Sacrifice', 'Limits'],
        "picture":"https://raw.githubusercontent.com/AlmirPaulo/TarotAPI/main/cards/rws/12.jpg",
            },
        {"title":"The Death",
        "major_arcana":True,
        "id":13,
        "keywords":['Changes', 'New beginings', 'Ends'],
        "picture":"https://raw.githubusercontent.com/AlmirPaulo/TarotAPI/main/cards/rws/13.jpg",
            },
        {"title":"The Temperance",
        "major_arcana":True,
        "id":14,
        "keywords":['Harmony','Moderation', 'Balance'],
        "picture":"https://raw.githubusercontent.com/AlmirPaulo/TarotAPI/main/cards/rws/14.jpg",
            },
        {"title":"The Devil",
        "major_arcana":True,
        "id":15,
        "keywords":['Material matters', 'Necessities', 'Addictions'],
        "picture":"https://raw.githubusercontent.com/AlmirPaulo/TarotAPI/main/cards/rws/15.jpg",
            },
        {"title":"The Tower",
        "major_arcana":True,
        "id":16,
        "keywords":['Abrupt changes', 'Falls'],
        "picture":"https://raw.githubusercontent.com/AlmirPaulo/TarotAPI/main/cards/rws/16.jpg",
            },
        {"title":"The Star",
        "major_arcana":True,
        "id":17,
        "keywords":['Hope', 'Faith'],
        "picture":"https://raw.githubusercontent.com/AlmirPaulo/TarotAPI/main/cards/rws/17.jpg",
            },
        {"title":"The Moon",
        "major_arcana":True,
        "id":18,
        "keywords":['Sadness','Fear', 'Illusion', 'Hidden enemies' ],
        "picture":"https://raw.githubusercontent.com/AlmirPaulo/TarotAPI/main/cards/rws/18.jpg",
            },
        {"title":"The Sun",
        "major_arcana":True,
        "id":19,
        "keywords":['Joy', 'Happyness', 'Clarity'],
        "picture":"https://raw.githubusercontent.com/AlmirPaulo/TarotAPI/main/cards/rws/19.jpg",
            },
        {"title":"The Judgement",
        "major_arcana":True,
        "id":20,
        "keywords":['Calling', 'Self-Judgement'],
        "picture":"https://raw.githubusercontent.com/AlmirPaulo/TarotAPI/main/cards/rws/20.jpg",
            },
        {"title":"The World",
        "major_arcana":True,
        "id":21,
        "keywords":['Conclusion', 'The whole'],
        "picture":"https://raw.githubusercontent.com/AlmirPaulo/TarotAPI/main/cards/rws/21.jpg",
            },
        {"title":"",
        "major_arcana":"",
        "id":"",
        "keywords":[],
        "picture":"",
            }]
        }
