cards = {
    "cards": [
        {
            "title": "The Fool",
            "major_arcana": True,
            "id": 0,
            "keywords": ["Ignorance", "Innocence", "Begginings", "Freedom"],
            "picture": "https://raw.githubusercontent.com/AlmirPaulo/TarotAPI/main/cards/rws/0.jpg",
            "questions": [
                "From where is he coming?",
                "Where is he going?",
                "What is he carrying in the bag?",
                "Is the dog a friend?",
            ],
        },
        {
            "title": "The Magician",
            "major_arcana": True,
            "id": 1,
            "keywords": ["Skill", "Rogueness", "Intelligence", "To take action"],
            "picture": "https://raw.githubusercontent.com/AlmirPaulo/TarotAPI/main/cards/rws/1.jpg",
            "questions": [
                "What is he doing?",
                "Why he is in this stance?",
                "Why he needs a sword?",
                "Why he needs a chalice?",
                "Why he needs a staff?",
                "Why he needs a coin?",
                "What about the flowers in front of him?",
            ],
        },
        {
            "title": "The High Priestess",
            "major_arcana": True,
            "id": 2,
            "keywords": ["Silence", "Secrets", "Intuition"],
            "picture": "https://raw.githubusercontent.com/AlmirPaulo/TarotAPI/main/cards/rws/2.jpg",
            "questions": [
                "Who/What is she?",
                "Where she is?",
                "What is the subject of the book in her hands?",
                "Why the moon are at her feet?",
                "What is she hiding behind the veils?",
            ],
        },
        {
            "title": "The Empress",
            "major_arcana": True,
            "id": 3,
            "keywords": ["Mother", "Feminine", "Fertility", "Abundance", "Creation"],
            "picture": "https://raw.githubusercontent.com/AlmirPaulo/TarotAPI/main/cards/rws/3.jpg",
            "questions": [
                "Who/What is she?",
                "Where she is?",
                "There is a sign inside a heart below the throne. What you think about it?",
                "What you think about her throne?",
                "Is she pregnant?",
            ],
        },
        {
            "title": "The Emperor",
            "major_arcana": True,
            "id": 4,
            "keywords": ["Father", "Masculine", "Power", "Authority"],
            "picture": "https://raw.githubusercontent.com/AlmirPaulo/TarotAPI/main/cards/rws/4.jpg",
            "questions": [
                "Who/What is he?",
                "Where he is?",
                "There is the head of an animal entailed in his throne. What you think about it?",
                "What you think about his throne?",
                "Why he is armored?",
            ],
        },
        {
            "title": "The Hierophant",
            "major_arcana": True,
            "id": 5,
            "keywords": ["Dogma", "Wisdom Master", "Structure"],
            "picture": "https://raw.githubusercontent.com/AlmirPaulo/TarotAPI/main/cards/rws/5.jpg",
            "questions": [
                "What the man in the throne are saying to the people?",
                "Why people are listen to this man?",
                "Would you like to hear what he is saying too? Why?",
                "Where they are?",
            ],
        },
        {
            "title": "The Lovers",
            "major_arcana": True,
            "id": 6,
            "keywords": ["Choices", "Decisions"],
            "picture": "https://raw.githubusercontent.com/AlmirPaulo/TarotAPI/main/cards/rws/6.jpg",
            "questions": [
                "What you think is happening between the 3 main figures?",
                "What is that tree behind the man?",
                "What is that tree behind the woman?",
            ],
        },
        {
            "title": "The Chariot",
            "major_arcana": True,
            "id": 7,
            "keywords": ["Will power", "Movements"],
            "picture": "https://raw.githubusercontent.com/AlmirPaulo/TarotAPI/main/cards/rws/7.jpg",
            "questions": [
                "Who/What is this man?",
                "From where he is coming?",
                "Where is he going?",
                "What about his armor?",
                "He is in a charriot. Why?",
                "The chariot is pulled by sphinxes. What it means?",
                "Why there is a white and a black sphinx?",
            ],
        },
        {
            "title": "The Strength",
            "major_arcana": True,
            "id": 8,
            "keywords": ["Control", "Self-control", "Courage"],
            "picture": "https://raw.githubusercontent.com/AlmirPaulo/TarotAPI/main/cards/rws/8.jpg",
            "quesions": [
                "Who/What is she?",
                "What is the lion?",
                "What she is doing to the lion?",
                "How can she do this?",
            ],
        },
        {
            "title": "The Hermit",
            "major_arcana": True,
            "id": 9,
            "keywords": ["Loneliness", "Solitude", "Time for meditation"],
            "picture": "https://raw.githubusercontent.com/AlmirPaulo/TarotAPI/main/cards/rws/9.jpg",
            "questions": [
                "Who/What is he?",
                "What is he looking for?",
                "What means to be a hermit?",
                "Why he has a cloak?",
                "Why he has a staff?",
                "Why he has a lantern?",
            ],
        },
        {
            "title": "The Wheel of Fortune",
            "major_arcana": True,
            "id": 10,
            "keywords": ["Cycles", "Luck"],
            "picture": "https://raw.githubusercontent.com/AlmirPaulo/TarotAPI/main/cards/rws/10.jpg",
            "questions": [
                "What is this wheel?",
                "What represents the sphinx at the top of the wheel?",
                "What represents the snake going down?",
                "What represents that figure (Anubis?) going up?",
                "Why each figure is in its respective position?",
            ],
        },
        {
            "title": "The Justice",
            "major_arcana": True,
            "id": 11,
            "keywords": ["Rationality", "Justice", "Fairness"],
            "picture": "https://raw.githubusercontent.com/AlmirPaulo/TarotAPI/main/cards/rws/11.jpg",
            "questions": [
                "Why she has a scale of dishes?",
                "Why she has a sword?",
                "Where she is?",
                "What about her throne?",
            ],
        },
        {
            "title": "The Hanged Man",
            "major_arcana": True,
            "id": 12,
            "keywords": ["Sacrifice", "Limits"],
            "picture": "https://raw.githubusercontent.com/AlmirPaulo/TarotAPI/main/cards/rws/12.jpg",
            "questions": ["Why he hangs?", "Is he imprisioned?", "Why he has a halo?"],
        },
        {
            "title": "The Death",
            "major_arcana": True,
            "id": 13,
            "keywords": ["Changes", "New beginings", "Ends"],
            "picture": "https://raw.githubusercontent.com/AlmirPaulo/TarotAPI/main/cards/rws/13.jpg",
            "questions": [
                "What the Death Knight brings?",
                "The king is dead, but the prince is amazed. What it means?",
                "The sun in the background, is rising or setting?",
                "What the Death Knigth and the Pope (Hierophant) are talking about?",
            ],
        },
        {
            "title": "The Temperance",
            "major_arcana": True,
            "id": 14,
            "keywords": ["Harmony", "Moderation", "Balance"],
            "picture": "https://raw.githubusercontent.com/AlmirPaulo/TarotAPI/main/cards/rws/14.jpg",
            "questions": [
                "The angel is a man or a woman?",
                "It are mixing the waters from the right chalice with the left chalice. What it means?",
                "It has a foot on the water and the other on the soil. What it means?",
                "The sun in the background, is rising or setting?",
            ],
        },
        {
            "title": "The Devil",
            "major_arcana": True,
            "id": 15,
            "keywords": ["Material matters", "Necessities", "Addictions"],
            "picture": "https://raw.githubusercontent.com/AlmirPaulo/TarotAPI/main/cards/rws/15.jpg",
            "questions": [
                "What represents this main figure?",
                "There are other two figures chained to it. What it means?",
                "The main figure points the fire down. What it means?",
                "Why the main figure is in that stance?",
            ],
        },
        {
            "title": "The Tower",
            "major_arcana": True,
            "id": 16,
            "keywords": ["Abrupt changes", "Falls"],
            "picture": "https://raw.githubusercontent.com/AlmirPaulo/TarotAPI/main/cards/rws/16.jpg",
            "questions": [
                "What a tower represents?",
                "The tower has a crown. What it means?",
                "A bolt strikes and destroys the tower. What it means?",
            ],
        },
        {
            "title": "The Star",
            "major_arcana": True,
            "id": 17,
            "keywords": ["Hope", "Faith"],
            "picture": "https://raw.githubusercontent.com/AlmirPaulo/TarotAPI/main/cards/rws/17.jpg",
            "questions": [
                "Who/What is she?",
                "Why she is naked?",
                "Why she is pouring out her waters?",
                "When you use to look at the stars?",
            ],
        },
        {
            "title": "The Moon",
            "major_arcana": True,
            "id": 18,
            "keywords": ["Sadness", "Fear", "Illusion", "Hidden enemies"],
            "picture": "https://raw.githubusercontent.com/AlmirPaulo/TarotAPI/main/cards/rws/18.jpg",
            "questions": [
                "Where this crab/lobster is?",
                "Where the crab/lobster is going?",
                "What the dog and the wolf are doing?",
                "What do you think will happen in this scene?",
            ],
        },
        {
            "title": "The Sun",
            "major_arcana": True,
            "id": 19,
            "keywords": ["Joy", "Happyness", "Clarity"],
            "picture": "https://raw.githubusercontent.com/AlmirPaulo/TarotAPI/main/cards/rws/19.jpg",
            "questions": [
                "Who/What is the boy?",
                "What he is doing?",
                "Where he is?",
                "What the sun does?",
            ],
        },
        {
            "title": "The Judgement",
            "major_arcana": True,
            "id": 20,
            "keywords": ["Calling", "Self-Judgement"],
            "picture": "https://raw.githubusercontent.com/AlmirPaulo/TarotAPI/main/cards/rws/20.jpg",
            "questions": [
                "This scene sounds familiar?",
                "What the angel is doing?",
                "What an angel represents?",
                "What is 'comming back from the deads'?",
                "And what means 'to be back from de deads'?",
            ],
        },
        {
            "title": "The World",
            "major_arcana": True,
            "id": 21,
            "keywords": ["Conclusion", "The whole"],
            "picture": "https://raw.githubusercontent.com/AlmirPaulo/TarotAPI/main/cards/rws/21.jpg",
            "questions": [
                "What a bull means?",
                "What a lion means?",
                "What an eagle means?",
                "What the human figure on the corner means?",
                "Who/What that woman on the middle is?",
            ],
        },
        {
            "title": "",
            "major_arcana": "",
            "id": "",
            "keywords": [],
            "picture": "",
        },
    ]
}
